server:
   port: 8081
spring:
   application:
      name: spring-security-app
   security:
      user:
         name: userForInMemoryAuthentication
         password: passForInMemoryAuthentication
#myapp: read from vm args of run configuration or system environment variable
#   password: secret
